name: mood_diary
description: "A new Flutter project."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ^3.5.4


dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_bloc: ^9.0.0
  bloc: ^9.0.0
  intl: ^0.19.0
  flutter_svg: ^2.0.17
  flutter_form_builder: ^9.7.0
  equatable: ^2.0.7
  meta: ^1.15.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0


flutter:
  uses-material-design: true
  assets: 
      - assets/svg/
      - assets/icons/
